cont = int(1)
valor = str(input('qual o valor da tonelada?   '))
valor = str(valor).replace(',','.')
valor2 = float(valor)
while (cont>=1):
    print("                                                   ")
    print("                                                   ")
    print("                                                   ")
    peso = str(input('qual o peso da nota ?   '))
    peso = str(peso).replace(',','.')
    peso2 = float(peso)
    calculo = "%.2f" %((peso2/1000)*valor2)
    print("____________________________________________________")
    print ('o valor do frete é R$:',calculo,)
    print("____________________________________________________")
    print("                                                   ")
    print ('(1) p/ para continuar (0) p/ parar')
    cont = int(input("1 ou 0 ?   "))
